categories:
  - title: "Breaking Changes"
    labels:
      - "breaking change"
  - title: "Intent Updates"
    labels:
      - "intent"
  - title: "Sentence Updates"
    collapse-after: 1
    labels:
      - "sentence"
  - title: "Dependencies"
    collapse-after: 1
    labels:
      - "dependencies"
template: |
  ## What's Changed

  $CHANGES
