#!/usr/bin/env bash
set -eo pipefail

# Directory of *this* script
this_dir="$( cd "$( dirname "$0" )" && pwd )"

base_dir="$(realpath "${this_dir}/..")"

# Path to virtual environment
: "${venv:=${base_dir}/venv}"

if [ -d "${venv}" ]; then
    # Activate virtual environment if available
    source "${venv}/bin/activate"
fi

python_files=()
python_files+=("${base_dir}/tests"/*.py)
python_files+=("${base_dir}/script/intentfest"/*.py)

# Format code
black "${python_files[@]}" --check
isort "${python_files[@]}" --check

# Check
flake8 "${python_files[@]}"
pylint "${python_files[@]}"
mypy "${python_files[@]}"

python3 -m script.intentfest validate

# prettier
pre-commit run prettier --all-files --verbose
