#!/usr/bin/env bash
set -eo pipefail

# Directory of *this* script
this_dir="$( cd "$( dirname "$0" )" && pwd )"

# Base directory of repo
base_dir="$(realpath "${this_dir}/..")"

# Path to virtual environment
: "${venv:=${base_dir}/venv}"

if [ -d "${venv}" ]; then
    # Activate virtual environment if available
    source "${venv}/bin/activate"
fi

package_dir="${base_dir}/package"
intents_dir="${package_dir}/home_assistant_intents"
data_dir="${intents_dir}/data"
rm -rf "${data_dir}"
rm -rf "${base_dir}/package/dist"

python3 -m script.intentfest merged_output "${data_dir}"
python3 "${package_dir}/script/write_languages.py" "${data_dir}" > "${intents_dir}/domains.py"
black "${intents_dir}/domains.py"
cd "${base_dir}/package" && python3 -m build

echo "See: ${base_dir}/package/dist"
